### ISSUE TITLE
Strange package name (Payload)

### ISSUE THREAD

**Issue by matheusgr** [ruanres/qma-daca#4]
https://github.com/ruanres/qma-daca/blob/b76f24ec800c4cc9eb26a5442fcaf42e8d6dedb2/backend/src/main/java/ruan/eloy/backend/payload/SignUpRequest.java#L1

Feel free to call that package [DTO](https://martinfowler.com/eaaCatalog/dataTransferObject.html).

**Comment by ruanres** [comment]
I Changed the package name to dto, as it was recommended.
